// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPDJ4NTEiKuMItHB_hUOeekpzQEjVhDtA',
    appId: '1:398637772626:web:81aad3f1f48bc39cdf548b',
    messagingSenderId: '398637772626',
    projectId: 'luxall',
    authDomain: 'luxall.firebaseapp.com',
    storageBucket: 'luxall.firebasestorage.app',
    measurementId: 'G-5H4ZLPGJE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA11nOjUbtStGfAAF-oKTPtsSodbdQxEXE',
    appId: '1:398637772626:android:764593f32c08ea4ddf548b',
    messagingSenderId: '398637772626',
    projectId: 'luxall',
    storageBucket: 'luxall.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv7ejCRxfWc2opQ8b2nXbSC1pbfBeF2tk',
    appId: '1:398637772626:ios:82a620d9bd89dc88df548b',
    messagingSenderId: '398637772626',
    projectId: 'luxall',
    storageBucket: 'luxall.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv7ejCRxfWc2opQ8b2nXbSC1pbfBeF2tk',
    appId: '1:398637772626:ios:82a620d9bd89dc88df548b',
    messagingSenderId: '398637772626',
    projectId: 'luxall',
    storageBucket: 'luxall.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPDJ4NTEiKuMItHB_hUOeekpzQEjVhDtA',
    appId: '1:398637772626:web:06501c2a315d6b0fdf548b',
    messagingSenderId: '398637772626',
    projectId: 'luxall',
    authDomain: 'luxall.firebaseapp.com',
    storageBucket: 'luxall.firebasestorage.app',
    measurementId: 'G-LRBK2HSFMH',
  );

}