import 'package:flutter/cupertino.dart';

class MentalHealthTask {
  final String id;
  final String title;
  final String description;
  final IconData icon;
  final String duration;
  final String state;
  final String category;

  const MentalHealthTask({
    required this.id,
    required this.title,
    required this.description,
    required this.icon,
    required this.duration,
    required this.state,
    required this.category,
  });
}

class MentalHealthCategory {
  final String name;
  final double weight;
  final List<MentalHealthTask> tasks;

  const MentalHealthCategory({
    required this.name,
    required this.weight,
    required this.tasks,
  });
}

class MentalHealthState {
  final String name;
  final String description;
  final double minScore;
  final double maxScore;

  const MentalHealthState({
    required this.name,
    required this.description,
    required this.minScore,
    required this.maxScore,
  });
}

final List<MentalHealthState> mentalHealthStates = [
  const MentalHealthState(
    name: 'Critical State',
    description: 'You\'re under a lot of emotional strain. Let\'s focus on rest and building support.',
    minScore: 1.0,
    maxScore: 2.0,
  ),
  const MentalHealthState(
    name: 'Vulnerable State',
    description: 'You\'re managing, but some areas need attention. Let\'s create balance.',
    minScore: 2.1,
    maxScore: 3.0,
  ),
  const MentalHealthState(
    name: 'Stable State',
    description: 'You\'re in a good place, but there\'s room for growth. Let\'s strengthen your habits.',
    minScore: 3.1,
    maxScore: 4.0,
  ),
  const MentalHealthState(
    name: 'Thriving State',
    description: 'You\'re thriving! Let\'s maintain this momentum and help you grow further.',
    minScore: 4.1,
    maxScore: 5.0,
  ),
];

final List<MentalHealthTask> mentalHealthTasks = [
  MentalHealthTask(
    id: 'task_1',
    title: 'Deep Breathing Exercise',
    description: 'Take 5 minutes to practice deep breathing techniques.',
    icon: CupertinoIcons.wind,
    duration: '5 minutes',
    state: 'Critical State',
    category: 'Emotional Wellbeing',
  ),
  MentalHealthTask(
    id: 'task_2',
    title: 'Mindful Walking',
    description: 'Go for a 10-minute mindful walk, focusing on your surroundings.',
    icon: CupertinoIcons.arrow_right_circle,
    duration: '10 minutes',
    state: 'Critical State',
    category: 'Physical Activity',
  ),
  MentalHealthTask(
    id: 'task_3',
    title: 'Gratitude Journal',
    description: 'Write down three things you are grateful for today.',
    icon: CupertinoIcons.pencil,
    duration: '5 minutes',
    state: 'Critical State',
    category: 'Emotional Wellbeing',
  ),
  MentalHealthTask(
    id: 'task_4',
    title: 'Healthy Snack',
    description: 'Prepare and enjoy a nutritious snack with fruits and nuts.',
    icon: CupertinoIcons.leaf_arrow_circlepath,
    duration: '10 minutes',
    state: 'Vulnerable State',
    category: 'Physical Activity',
  ),
  MentalHealthTask(
    id: 'task_5',
    title: 'Social Connection',
    description: 'Reach out to a friend or family member for a chat.',
    icon: CupertinoIcons.person_2,
    duration: '15 minutes',
    state: 'Vulnerable State',
    category: 'Social Support',
  ),
  MentalHealthTask(
    id: 'task_6',
    title: 'Mindful Meditation',
    description: 'Practice a guided meditation session.',
    icon: CupertinoIcons.moon_stars,
    duration: '10 minutes',
    state: 'Vulnerable State',
    category: 'Emotional Wellbeing',
  ),
  MentalHealthTask(
    id: 'task_7',
    title: 'Exercise Routine',
    description: 'Complete a 20-minute workout session.',
    icon: CupertinoIcons.bolt,
    duration: '20 minutes',
    state: 'Stable State',
    category: 'Physical Activity',
  ),
  MentalHealthTask(
    id: 'task_8',
    title: 'Weekly Goal Setting',
    description: 'Set and break down your goals for the week ahead.',
    icon: CupertinoIcons.calendar_badge_plus,
    duration: '20 minutes',
    state: 'Stable State',
    category: 'Personal Growth',
  ),
  MentalHealthTask(
    id: 'task_9',
    title: 'Creative Expression',
    description: 'Engage in a creative activity like drawing or writing.',
    icon: CupertinoIcons.paintbrush,
    duration: '15 minutes',
    state: 'Stable State',
    category: 'Emotional Wellbeing',
  ),
  MentalHealthTask(
    id: 'task_10',
    title: 'Community Engagement',
    description: 'Participate in a community activity or volunteer work.',
    icon: CupertinoIcons.group,
    duration: '30 minutes',
    state: 'Thriving State',
    category: 'Social Support',
  ),
  MentalHealthTask(
    id: 'task_11',
    title: 'Learning New Skill',
    description: 'Start learning a new skill or hobby.',
    icon: CupertinoIcons.book,
    duration: '30 minutes',
    state: 'Thriving State',
    category: 'Personal Growth',
  ),
  MentalHealthTask(
    id: 'task_12',
    title: 'Nature Connection',
    description: 'Spend time in nature, observing and appreciating your surroundings.',
    icon: CupertinoIcons.tree,
    duration: '20 minutes',
    state: 'Thriving State',
    category: 'Physical Activity',
  ),
];

final List<MentalHealthCategory> mentalHealthCategories = [
  MentalHealthCategory(
    name: 'Emotional Care',
    weight: 0.2,
    tasks: [
      MentalHealthTask(
        id: 'emotional_critical_1',
        title: 'Deep Breathing',
        description: 'Take 5 minutes to focus on your breathing. Inhale for 4 counts, hold for 4, exhale for 4.',
        icon: CupertinoIcons.wind,
        duration: '5 minutes',
        state: 'Critical State',
        category: 'Emotional Care',
      ),
      MentalHealthTask(
        id: 'emotional_critical_2',
        title: 'Write Down Your Feelings',
        description: 'Spend 10 minutes writing about your current emotions and what triggered them.',
        icon: CupertinoIcons.pencil,
        duration: '10 minutes',
        state: 'Critical State',
        category: 'Emotional Care',
      ),
      MentalHealthTask(
        id: 'emotional_critical_3',
        title: 'Listen to a Calming Podcast',
        description: 'Listen to a short mindfulness or relaxation podcast.',
        icon: CupertinoIcons.headphones,
        duration: '10 minutes',
        state: 'Critical State',
        category: 'Emotional Care',
      ),
      MentalHealthTask(
        id: 'emotional_vulnerable_1',
        title: 'Gratitude Journal',
        description: 'Write down three things you\'re grateful for today.',
        icon: CupertinoIcons.heart,
        duration: '5 minutes',
        state: 'Vulnerable State',
        category: 'Emotional Care',
      ),
      MentalHealthTask(
        id: 'emotional_vulnerable_2',
        title: 'Listen to Calming Music',
        description: 'Put on some calming music and focus on your breathing.',
        icon: CupertinoIcons.music_note,
        duration: '10 minutes',
        state: 'Vulnerable State',
        category: 'Emotional Care',
      ),
      MentalHealthTask(
        id: 'emotional_vulnerable_3',
        title: 'Practice Positive Affirmations',
        description: 'Write and repeat three positive affirmations about yourself.',
        icon: CupertinoIcons.star,
        duration: '5 minutes',
        state: 'Vulnerable State',
        category: 'Emotional Care',
      ),
      MentalHealthTask(
        id: 'emotional_stable_1',
        title: 'Self-Reflection Prompt',
        description: 'Answer a self-reflection question about your emotional growth.',
        icon: CupertinoIcons.lightbulb,
        duration: '15 minutes',
        state: 'Stable State',
        category: 'Emotional Care',
      ),
      MentalHealthTask(
        id: 'emotional_stable_2',
        title: 'Mood Tracker',
        description: 'Track your mood throughout the day and note any patterns.',
        icon: CupertinoIcons.chart_bar,
        duration: '5 minutes',
        state: 'Stable State',
        category: 'Emotional Care',
      ),
      MentalHealthTask(
        id: 'emotional_stable_3',
        title: 'Plan a Self-Care Day',
        description: 'Plan activities for your next self-care day.',
        icon: CupertinoIcons.calendar,
        duration: '10 minutes',
        state: 'Stable State',
        category: 'Emotional Care',
      ),
      MentalHealthTask(
        id: 'emotional_thriving_1',
        title: 'Visualization Exercise',
        description: 'Visualize your ideal future and how it makes you feel.',
        icon: CupertinoIcons.eye,
        duration: '10 minutes',
        state: 'Thriving State',
        category: 'Emotional Care',
      ),
      MentalHealthTask(
        id: 'emotional_thriving_2',
        title: 'Write a Positive Letter',
        description: 'Write a letter to yourself about your strengths and achievements.',
        icon: CupertinoIcons.mail,
        duration: '15 minutes',
        state: 'Thriving State',
        category: 'Emotional Care',
      ),
      MentalHealthTask(
        id: 'emotional_thriving_3',
        title: 'Meditate on Long-Term Goals',
        description: 'Spend time meditating on your long-term goals and aspirations.',
        icon: CupertinoIcons.moon_stars,
        duration: '15 minutes',
        state: 'Thriving State',
        category: 'Emotional Care',
      ),
    ],
  ),
  MentalHealthCategory(
    name: 'Physical Well-Being',
    weight: 0.2,
    tasks: [
      MentalHealthTask(
        id: 'physical_critical_1',
        title: 'Drink a Glass of Water',
        description: 'Drink a full glass of water and take a moment to breathe.',
        icon: CupertinoIcons.drop,
        duration: '5 minutes',
        state: 'Critical State',
        category: 'Physical Well-Being',
      ),
      MentalHealthTask(
        id: 'physical_critical_2',
        title: 'Stretch for 5 Minutes',
        description: 'Do gentle stretches to release tension.',
        icon: CupertinoIcons.person_2,
        duration: '5 minutes',
        state: 'Critical State',
        category: 'Physical Well-Being',
      ),
      MentalHealthTask(
        id: 'physical_critical_3',
        title: 'Take 10 Deep Breaths',
        description: 'Focus on taking 10 deep, calming breaths.',
        icon: CupertinoIcons.wind,
        duration: '5 minutes',
        state: 'Critical State',
        category: 'Physical Well-Being',
      ),
      MentalHealthTask(
        id: 'physical_vulnerable_1',
        title: 'Go for a Walk',
        description: 'Take a 10-minute walk outside to boost your energy levels.',
        icon: CupertinoIcons.arrow_right_circle,
        duration: '10 minutes',
        state: 'Vulnerable State',
        category: 'Physical Well-Being',
      ),
      MentalHealthTask(
        id: 'physical_vulnerable_2',
        title: 'Prepare a Healthy Snack',
        description: 'Make a nutritious snack with fruits and nuts.',
        icon: CupertinoIcons.leaf_arrow_circlepath,
        duration: '10 minutes',
        state: 'Vulnerable State',
        category: 'Physical Well-Being',
      ),
      MentalHealthTask(
        id: 'physical_vulnerable_3',
        title: 'Do Light Yoga',
        description: 'Follow a gentle 10-minute yoga routine.',
        icon: CupertinoIcons.person_2,
        duration: '10 minutes',
        state: 'Vulnerable State',
        category: 'Physical Well-Being',
      ),
      MentalHealthTask(
        id: 'physical_stable_1',
        title: '20-Min Yoga',
        description: 'Follow a moderate yoga routine to improve flexibility.',
        icon: CupertinoIcons.person_2,
        duration: '20 minutes',
        state: 'Stable State',
        category: 'Physical Well-Being',
      ),
      MentalHealthTask(
        id: 'physical_stable_2',
        title: 'Balanced Meal Plan',
        description: 'Plan your next meal with a focus on balanced nutrition.',
        icon: CupertinoIcons.list_bullet,
        duration: '15 minutes',
        state: 'Stable State',
        category: 'Physical Well-Being',
      ),
      MentalHealthTask(
        id: 'physical_stable_3',
        title: 'Quick Cardio Session',
        description: 'Do a 15-minute cardio workout to boost endorphins.',
        icon: CupertinoIcons.bolt,
        duration: '15 minutes',
        state: 'Stable State',
        category: 'Physical Well-Being',
      ),
      MentalHealthTask(
        id: 'physical_thriving_1',
        title: 'Cardio Session',
        description: 'Complete a 30-minute cardio workout.',
        icon: CupertinoIcons.bolt,
        duration: '30 minutes',
        state: 'Thriving State',
        category: 'Physical Well-Being',
      ),
      MentalHealthTask(
        id: 'physical_thriving_2',
        title: 'Outdoor Adventure',
        description: 'Plan and go on an outdoor activity you enjoy.',
        icon: CupertinoIcons.sunrise,
        duration: '1 hour',
        state: 'Thriving State',
        category: 'Physical Well-Being',
      ),
      MentalHealthTask(
        id: 'physical_thriving_3',
        title: 'Try a New Fitness Class',
        description: 'Sign up for and attend a new fitness class.',
        icon: CupertinoIcons.person_3,
        duration: '1 hour',
        state: 'Thriving State',
        category: 'Physical Well-Being',
      ),
    ],
  ),
  MentalHealthCategory(
    name: 'Productivity & Organization',
    weight: 0.2,
    tasks: [
      MentalHealthTask(
        id: 'productivity_critical_1',
        title: 'Make a Simple To-Do List',
        description: 'Create a simple list of 3 achievable tasks for today.',
        icon: CupertinoIcons.checkmark_circle,
        duration: '5 minutes',
        state: 'Critical State',
        category: 'Productivity & Organization',
      ),
      MentalHealthTask(
        id: 'productivity_critical_2',
        title: 'Tidy One Small Space',
        description: 'Clean and organize one small area of your living space.',
        icon: CupertinoIcons.house,
        duration: '10 minutes',
        state: 'Critical State',
        category: 'Productivity & Organization',
      ),
      MentalHealthTask(
        id: 'productivity_critical_3',
        title: 'Prioritize One Task',
        description: 'Identify and focus on your most important task for today.',
        icon: CupertinoIcons.arrow_up_circle,
        duration: '10 minutes',
        state: 'Critical State',
        category: 'Productivity & Organization',
      ),
      MentalHealthTask(
        id: 'productivity_vulnerable_1',
        title: 'Plan Tomorrow\'s Top 3',
        description: 'Identify and plan your top 3 priorities for tomorrow.',
        icon: CupertinoIcons.calendar,
        duration: '10 minutes',
        state: 'Vulnerable State',
        category: 'Productivity & Organization',
      ),
      MentalHealthTask(
        id: 'productivity_vulnerable_2',
        title: 'Organize Digital Files',
        description: 'Clean up your digital workspace and organize files.',
        icon: CupertinoIcons.folder,
        duration: '15 minutes',
        state: 'Vulnerable State',
        category: 'Productivity & Organization',
      ),
      MentalHealthTask(
        id: 'productivity_vulnerable_3',
        title: 'Declutter Your Desk',
        description: 'Clean and organize your workspace for better focus.',
        icon: CupertinoIcons.desktopcomputer,
        duration: '15 minutes',
        state: 'Vulnerable State',
        category: 'Productivity & Organization',
      ),
      MentalHealthTask(
        id: 'productivity_stable_1',
        title: 'Weekly Goal Setting',
        description: 'Set and break down your goals for the week ahead.',
        icon: CupertinoIcons.calendar_badge_plus,
        duration: '20 minutes',
        state: 'Stable State',
        category: 'Productivity & Organization',
      ),
      MentalHealthTask(
        id: 'productivity_stable_2',
        title: 'Reflect on Achievements',
        description: 'Review and celebrate your recent accomplishments.',
        icon: CupertinoIcons.star,
        duration: '15 minutes',
        state: 'Stable State',
        category: 'Productivity & Organization',
      ),
      MentalHealthTask(
        id: 'productivity_stable_3',
        title: 'Complete a Pending Task',
        description: 'Finish one task that\'s been on your list for a while.',
        icon: CupertinoIcons.checkmark_seal,
        duration: '30 minutes',
        state: 'Stable State',
        category: 'Productivity & Organization',
      ),
      MentalHealthTask(
        id: 'productivity_thriving_1',
        title: 'Tackle a Passion Project',
        description: 'Work on a project that excites and motivates you.',
        icon: CupertinoIcons.heart_circle,
        duration: '30 minutes',
        state: 'Thriving State',
        category: 'Productivity & Organization',
      ),
      MentalHealthTask(
        id: 'productivity_thriving_2',
        title: 'Start a New Skill',
        description: 'Begin learning a new skill that interests you.',
        icon: CupertinoIcons.book,
        duration: '20 minutes',
        state: 'Thriving State',
        category: 'Productivity & Organization',
      ),
      MentalHealthTask(
        id: 'productivity_thriving_3',
        title: 'Map Out Long-Term Goals',
        description: 'Create a detailed plan for your long-term goals.',
        icon: CupertinoIcons.map,
        duration: '30 minutes',
        state: 'Thriving State',
        category: 'Productivity & Organization',
      ),
    ],
  ),
  MentalHealthCategory(
    name: 'Creativity & Joy',
    weight: 0.2,
    tasks: [
      MentalHealthTask(
        id: 'creativity_critical_1',
        title: 'Doodle for 5 Minutes',
        description: 'Let your mind wander and doodle freely.',
        icon: CupertinoIcons.paintbrush,
        duration: '5 minutes',
        state: 'Critical State',
        category: 'Creativity & Joy',
      ),
      MentalHealthTask(
        id: 'creativity_critical_2',
        title: 'Listen to a Comforting Song',
        description: 'Listen to a song that brings you comfort.',
        icon: CupertinoIcons.music_note,
        duration: '5 minutes',
        state: 'Critical State',
        category: 'Creativity & Joy',
      ),
      MentalHealthTask(
        id: 'creativity_critical_3',
        title: 'Watch a Short Comedy Clip',
        description: 'Watch something that makes you laugh.',
        icon: CupertinoIcons.play_circle,
        duration: '5 minutes',
        state: 'Critical State',
        category: 'Creativity & Joy',
      ),
      MentalHealthTask(
        id: 'creativity_vulnerable_1',
        title: 'Try a New Recipe',
        description: 'Cook something new and exciting.',
        icon: CupertinoIcons.cube,
        duration: '30 minutes',
        state: 'Vulnerable State',
        category: 'Creativity & Joy',
      ),
      MentalHealthTask(
        id: 'creativity_vulnerable_2',
        title: 'Watch a Feel-Good Movie',
        description: 'Watch a movie that lifts your spirits.',
        icon: CupertinoIcons.play_circle,
        duration: '2 hours',
        state: 'Vulnerable State',
        category: 'Creativity & Joy',
      ),
      MentalHealthTask(
        id: 'creativity_vulnerable_3',
        title: 'Take Photos of Nature',
        description: 'Go outside and capture beautiful moments in nature.',
        icon: CupertinoIcons.camera,
        duration: '20 minutes',
        state: 'Vulnerable State',
        category: 'Creativity & Joy',
      ),
      MentalHealthTask(
        id: 'creativity_stable_1',
        title: 'Start a Creative Project',
        description: 'Begin a new creative project you\'ve been thinking about.',
        icon: CupertinoIcons.paintbrush,
        duration: '30 minutes',
        state: 'Stable State',
        category: 'Creativity & Joy',
      ),
      MentalHealthTask(
        id: 'creativity_stable_2',
        title: 'Learn a New Skill',
        description: 'Start learning a new creative skill.',
        icon: CupertinoIcons.book,
        duration: '20 minutes',
        state: 'Stable State',
        category: 'Creativity & Joy',
      ),
      MentalHealthTask(
        id: 'creativity_stable_3',
        title: 'Paint or Draw Something Fun',
        description: 'Create something just for fun and enjoyment.',
        icon: CupertinoIcons.paintbrush,
        duration: '20 minutes',
        state: 'Stable State',
        category: 'Creativity & Joy',
      ),
      MentalHealthTask(
        id: 'creativity_thriving_1',
        title: 'Join an Art Class',
        description: 'Sign up for an art class to develop your skills.',
        icon: CupertinoIcons.person_3,
        duration: '1 hour',
        state: 'Thriving State',
        category: 'Creativity & Joy',
      ),
      MentalHealthTask(
        id: 'creativity_thriving_2',
        title: 'Share Your Work',
        description: 'Share your creative work with others.',
        icon: CupertinoIcons.share,
        duration: '15 minutes',
        state: 'Thriving State',
        category: 'Creativity & Joy',
      ),
      MentalHealthTask(
        id: 'creativity_thriving_3',
        title: 'Write a Short Story',
        description: 'Create a short story from your imagination.',
        icon: CupertinoIcons.pencil,
        duration: '30 minutes',
        state: 'Thriving State',
        category: 'Creativity & Joy',
      ),
    ],
  ),
  MentalHealthCategory(
    name: 'Social Connection',
    weight: 0.2,
    tasks: [
      MentalHealthTask(
        id: 'social_critical_1',
        title: 'Text Someone You Trust',
        description: 'Reach out to someone you trust for support.',
        icon: CupertinoIcons.chat_bubble,
        duration: '5 minutes',
        state: 'Critical State',
        category: 'Social Connection',
      ),
      MentalHealthTask(
        id: 'social_critical_2',
        title: 'Reach Out for Support',
        description: 'Contact a support group or counselor.',
        icon: CupertinoIcons.person_2,
        duration: '15 minutes',
        state: 'Critical State',
        category: 'Social Connection',
      ),
      MentalHealthTask(
        id: 'social_critical_3',
        title: 'Join an Online Community',
        description: 'Find and join an online support community.',
        icon: CupertinoIcons.group,
        duration: '15 minutes',
        state: 'Critical State',
        category: 'Social Connection',
      ),
      MentalHealthTask(
        id: 'social_vulnerable_1',
        title: 'Call a Friend',
        description: 'Have a phone call with a friend.',
        icon: CupertinoIcons.phone,
        duration: '15 minutes',
        state: 'Vulnerable State',
        category: 'Social Connection',
      ),
      MentalHealthTask(
        id: 'social_vulnerable_2',
        title: 'Plan a Coffee Date',
        description: 'Arrange to meet a friend for coffee.',
        icon: CupertinoIcons.calendar,
        duration: '15 minutes',
        state: 'Vulnerable State',
        category: 'Social Connection',
      ),
      MentalHealthTask(
        id: 'social_vulnerable_3',
        title: 'Send an Encouraging Message',
        description: 'Send a supportive message to someone who needs it.',
        icon: CupertinoIcons.chat_bubble,
        duration: '5 minutes',
        state: 'Vulnerable State',
        category: 'Social Connection',
      ),
      MentalHealthTask(
        id: 'social_stable_1',
        title: 'Join a Social Activity',
        description: 'Participate in a group activity or event.',
        icon: CupertinoIcons.person_3,
        duration: '1 hour',
        state: 'Stable State',
        category: 'Social Connection',
      ),
      MentalHealthTask(
        id: 'social_stable_2',
        title: 'Start a Group Chat',
        description: 'Create a group chat with friends for regular check-ins.',
        icon: CupertinoIcons.chat_bubble_2,
        duration: '10 minutes',
        state: 'Stable State',
        category: 'Social Connection',
      ),
      MentalHealthTask(
        id: 'social_stable_3',
        title: 'Plan a Virtual Hangout',
        description: 'Organize an online gathering with friends.',
        icon: CupertinoIcons.video_camera,
        duration: '15 minutes',
        state: 'Stable State',
        category: 'Social Connection',
      ),
      MentalHealthTask(
        id: 'social_thriving_1',
        title: 'Host a Small Gathering',
        description: 'Host a small social gathering with friends.',
        icon: CupertinoIcons.house,
        duration: '2 hours',
        state: 'Thriving State',
        category: 'Social Connection',
      ),
      MentalHealthTask(
        id: 'social_thriving_2',
        title: 'Volunteer for a Cause',
        description: 'Find and participate in a volunteer opportunity.',
        icon: CupertinoIcons.heart_circle,
        duration: '2 hours',
        state: 'Thriving State',
        category: 'Social Connection',
      ),
      MentalHealthTask(
        id: 'social_thriving_3',
        title: 'Plan a Weekend Getaway',
        description: 'Organize a weekend trip with friends.',
        icon: CupertinoIcons.airplane,
        duration: '30 minutes',
        state: 'Thriving State',
        category: 'Social Connection',
      ),
    ],
  ),
]; 